# XTF Real-Time Pattern Analysis Pipeline Configuration
# Job: scm_xtf_54782_etl_proc_pattern_flow_rt_patternanalysis_prc_cmd
# Pipeline: Real-Time ML Pattern Analysis System

pipeline:
  name: "XTF_ML_Pattern_Analysis"
  version: "2.0.1"
  description: "Machine learning pattern analysis for fraud detection"
  owner: "xtf_ml_team@scm.com"
  business_unit: "Risk_Technology_Framework"
  
source_config:
  - source_name: "feature_store"
    source_type: "delta_table"
    source_database: "xtf_ml_db"
    source_format: "delta"
    source_columns:
      - name: "customer_id"
        type: "string"
        nullable: false
      - name: "feature_timestamp"
        type: "timestamp"
        nullable: false
      - name: "avg_transaction_amount_7d"
        type: "double"
        nullable: false
      - name: "transaction_frequency_7d"
        type: "double"
        nullable: false
      - name: "unique_merchants_7d"
        type: "integer"
        nullable: false
      - name: "weekend_activity_ratio"
        type: "double"
        nullable: false
      - name: "high_risk_merchant_ratio"
        type: "double"
        nullable: false
      - name: "cross_border_transaction_ratio"
        type: "double"
        nullable: false
      - name: "customer_tenure_days"
        type: "integer"
        nullable: false

target_config:
  - target_name: "pattern_predictions"
    target_type: "delta_table"
    target_database: "xtf_ml_db"
    target_table: "pattern_analysis_predictions"
    target_location: "s3://xtf-pattern-analysis/predictions/"
    target_format: "delta"
    target_write_mode: "append"
    target_partition_by: 
      - "prediction_date"
      - "model_version"
    target_optimize_write: true
    target_auto_compact: true
    target_columns:
      - name: "prediction_id"
        type: "string"
        nullable: false
      - name: "customer_id"
        type: "string"
        nullable: false
      - name: "transaction_id"
        type: "string"
        nullable: true
      - name: "prediction_timestamp"
        type: "timestamp"
        nullable: false
      - name: "prediction_date"
        type: "date"
        nullable: false
      - name: "model_version"
        type: "string"
        nullable: false
      - name: "fraud_probability"
        type: "double"
        nullable: false
      - name: "pattern_type"
        type: "string"
        nullable: false
      - name: "confidence_score"
        type: "double"
        nullable: false
      - name: "feature_importance"
        type: "map<string,double>"
        nullable: false
      - name: "anomaly_score"
        type: "double"
        nullable: false
      - name: "risk_factors"
        type: "array<string>"
        nullable: false

processing:
  stream_processing:
    trigger: "4 minutes"
    batch_size: 800
    parallelism: 25
    checkpoint_interval: "4 minutes"
    
  machine_learning:
    model_registry: "s3://xtf-ml-models/fraud-patterns/v2.1/"
    models:
      - name: "isolation_forest"
        version: "2.1.3"
        path: "isolation_forest/model.pkl"
        threshold: 0.7
      - name: "random_forest_classifier"
        version: "2.0.8"
        path: "random_forest/model.pkl" 
        threshold: 0.75
      - name: "xgboost_classifier"
        version: "1.9.2"
        path: "xgboost/model.pkl"
        threshold: 0.8
    ensemble_weights: [0.3, 0.4, 0.3]
    feature_scaling: "standard_scaler"
    
  pattern_detection:
    algorithms: ["clustering", "time_series_analysis", "graph_analysis"]
    time_windows: [10, 30, 60, 240] # minutes
    anomaly_threshold: 0.85
    
  monitoring:
    metrics_enabled: true
    model_drift_detection: true
    alert_thresholds:
      processing_delay_seconds: 240
      prediction_accuracy_threshold: 0.85
      model_drift_threshold: 0.1
