job_config:
  job_name: scm_fc_64173_etl_proc_sanctions_flow_dly_sanctionscheck_prc_cmd
  job_id: 64173
  domain: fc
  process_type: sanctions_flow
  frequency: daily
  description: "Daily ETL process for sanctions screening and compliance"
  
source_config:
  source_type: database
  connection:
    host: scm_fc-db02.internal
    source_database: fc_source_db
    schema: sanctions_data
  tables:
    - source_table: sanctions_lists
      source_location: s3://fc_source_db/sanctions_lists/
      columns:
        - list_id
        - entity_name
        - entity_type
        - aliases
        - jurisdiction
        - sanction_type
        - effective_date
        - list_source
        - confidence_score
        
target_config:
  target_type: database
  connection:
    host: scm-dwh-cluster.internal
    target_database: fc_analytics_db
    schema: sanctions_monitoring
  tables:
    - target_table: daily_sanctions_screening
      target_location: s3://fc_analytics_db/daily_sanctions_screening/
      columns:
        - process_date
        - customer_id
        - total_matches
        - highest_match_score
        - sanction_risk_level
        - requires_manual_review
        - _cleared_matches
        - escalation_required
        - last_screening_date
        - last_updated
      partition_key: process_date
      
processing_config:
  batch_size: 50000
  parallel_threads: 10
  data_quality_checks:
    - null_check: customer_id, entity_name
    - range_check: match_score [0,100]
    - date_check: effective_date
  transformations:
    - fuzzy_name_matching
    - calculate_risk_scores
    - _clear_false_positives
    - flag_high_risk_matches
    
schedule_config:
  start_time: "00:30"
  timezone: "strlia/Sydney"
  dependencies:
    - sanctions_list_updates
  
monitoring_config:
  sla_hours: 2
  alert_recipients:
    - sanctions-team@scm.com.
    - compliance@scm.com.
  metrics:
    - matches_requiring_review
    - false_positive_rate
    - screening_coverage
    - processing_time
