# XTF Real-Time Velocity Check Pipeline Configuration
# Job: scm_xtf_89345_etl_proc_velocity_flow_rt_velocitycheck_prc_cmd
# Pipeline: Real-Time Velocity Analysis System

pipeline:
  name: "XTF_Velocity_Analysis"
  version: "1.1.8"
  description: "Real-time velocity checking for transaction patterns"
  owner: "xtf_analytics@scm.com"
  business_unit: "Risk_Technology_Framework"

source_tables:
  - source_name: "velocity_patterns"
    source_type: "delta_table"
    source_database: "xtf_reference_db"
    source_table: "customer_velocity_patterns"
    source_location: "s3://xtf-reference-data/velocity-patterns/"
    source_format: "delta"
    source_columns:
      - name: "customer_id"
        type: "string"
        nullable: false
      - name: "avg_daily_transactions"
        type: "integer"
        nullable: false
      - name: "avg_daily_amount"
        type: "decimal(15,2)"
        nullable: false
      - name: "max_hourly_transactions"
        type: "integer"
        nullable: false
      - name: "typical_merchant_count"
        type: "integer"
        nullable: false
      - name: "velocity_score_baseline"
        type: "double"
        nullable: false
      - name: "last_updated"
        type: "timestamp"
        nullable: false

target_tables:
  - target_name: "velocity_analysis_results"
    target_type: "delta_table"
    target_database: "xtf_velocity_db"
    target_table: "real_time_velocity_analysis"
    target_location: "s3://xtf-velocity-analysis/results/"
    target_format: "delta"
    target_write_mode: "append"
    target_partition_by: 
      - "analysis_date"
      - "velocity_risk_level"
    target_optimize_write: true
    target_auto_compact: true
    target_columns:
      - name: "analysis_id"
        type: "string"
        nullable: false
      - name: "customer_id"
        type: "string"
        nullable: false
      - name: "analysis_timestamp"
        type: "timestamp"
        nullable: false
      - name: "analysis_date"
        type: "date"
        nullable: false
      - name: "time_window_minutes"
        type: "integer"
        nullable: false
      - name: "transaction_count"
        type: "integer"
        nullable: false
      - name: "total_amount"
        type: "decimal(15,2)"
        nullable: false
      - name: "unique_merchants"
        type: "integer"
        nullable: false
      - name: "velocity_score"
        type: "double"
        nullable: false
      - name: "velocity_risk_level"
        type: "string"
        nullable: false
      - name: "baseline_deviation"
        type: "double"
        nullable: false
      - name: "triggered_rules"
        type: "array<string>"
        nullable: false
        
processing:
  stream_processing:
    trigger: "3 minutes"
    batch_size: 500
    parallelism: 15
    checkpoint_interval: "3 minutes"
    
  velocity_analysis:
    time_windows: [5, 15, 30, 60, 120, 1440] # minutes
    velocity_thresholds:
      low: 0.3
      medium: 0.6
      high: 0.8
      critical: 0.95
    
  windowing:
    watermark_delay: "45 seconds"
    late_data_threshold: "5 minutes"
    
  monitoring:
    metrics_enabled: true
    alert_thresholds:
      processing_delay_seconds: 180
      velocity_alert_rate: 0.02
      error_rate_threshold: 0.01
