job_config:
  job_name: scm_fc_52896_etl_proc_aml_flow_dly_amlmonitoring_prc_cmd
  job_id: 52896
  domain: scm
  process_type: aml_flow
  frequency: daily
  description: "Daily ETL process for AML monitoring and compliance"
  
source_config:
  source_type: database
  connection:
    host: scm-scm-db01.internal
    source_database: scm_source_db
    schema: aml_data
  tables:
    - source_table: transaction_records
      source_location: s3://scm_source_db/transaction_records/
      columns:
        - transaction_id
        - customer_id
        - amount
        - currency
        - transaction_type
        - timestamp
        - counterparty_id
        - geographic_origin
        - risk_indicators
  
target_config:
  target_type: database
  connection:
    host: scm-dwh-cluster.internal
    target_database: scm_analytics_db
    target_schema: aml_monitoring
  tables:
    - target_table: daily_aml_alerts
      target_location: s3://scm_analytics_db/daily_aml_alerts/
      columns:
        - process_date
        - customer_id
        - alert_type
        - alert_severity
        - transaction_pattern
        - risk_score
        - investigation_status
        - regulatory_reportable
        - alert_date
        - last_updated
      partition_key: process_date
      
processing_config:
  batch_size: 25000
  parallel_threads: 8
  data_quality_checks:
    - null_check: customer_id, transaction_id
    - range_check: amount [0,999999999]
    - currency_code_check: currency
  transformations:
    - apply_aml_rules
    - calculate_transaction_patterns
    - generate_risk_scores
    - flag_suspicious_activities
    
schedule_config:
  start_time: "01:00"
  timezone: "stralia/Sydney"
  dependencies:
    - daily_transaction_ingestion
  
monitoring_config:
  sla_hours: 3
  alert_recipients:
    - aml-team@scm.com.
    - compliance@scm.com.
  metrics:
    - alerts_generated
    - high_risk_customers
    - regulatory_reports_pending
    - processing_time
