# XTF Real-Time Risk Scoring Pipeline Configuration
# Job: scm_xtf_73126_etl_proc_scoring_flow_rt_riskscoring_prc_cmd
# Pipeline: Real-Time Risk Scoring Engine

pipeline:
  name: "XTF_Risk_Scoring_Engine"
  version: "1.5.2"
  description: "Real-time risk scoring engine for transaction assessment"
  owner: "xtf_analytics@scm.com"
  business_unit: "Risk_Technology_Framework"

source_tables:
  - source_name: "pattern_predictions_stream"
    source_type: "kafka_stream"
    source_database: "xtf_streaming_db"
    source_table: "ml_pattern_predictions"
    source_location: "kafka://kafka-cluster-01:9092,kafka-cluster-02:9092"
    source_topic: "xtf-ml-insights"
    source_format: "avro"
    source_schema_registry: "http://schema-registry:8081"
    source_checkpoint_location: "s3://xtf-checkpoints/risk-scoring/"
    source_watermark:
      column: "insight_timestamp"
      delay: "30 seconds"
    source_columns:
      - name: "insight_id"
        type: "string"
        nullable: false
      - name: "customer_id"
        type: "string"
        nullable: false
      - name: "insight_timestamp"
        type: "timestamp"
        nullable: false
      - name: "pattern_detected"
        type: "string"
        nullable: false
      - name: "fraud_probability"
        type: "double"
        nullable: false
      - name: "recommended_action"
        type: "string"
        nullable: false

target_tables:
  - target_name: "real_time_risk_scores"
    target_type: "delta_table"
    target_database: "xtf_scoring_db"
    target_table: "customer_risk_scores_realtime"
    target_location: "s3://xtf-risk-scores/real-time/"
    target_format: "delta"
    target_write_mode: "append"
    target_partition_by: 
      - "scoring_date"
      - "risk_category"
    target_optimize_write: true
    target_auto_compact: true
    target_columns:
      - name: "risk_score_id"
        type: "string"
        nullable: false
      - name: "customer_id"
        type: "string"
        nullable: false
      - name: "scoring_timestamp"
        type: "timestamp"
        nullable: false
      - name: "scoring_date"
        type: "date"
        nullable: false
      - name: "final_risk_score"
        type: "double"
        nullable: false
      - name: "risk_category"
        type: "string"
        nullable: false
      - name: "model_version"
        type: "string"
        nullable: false
      - name: "component_scores"
        type: "map<string,double>"
        nullable: false
      - name: "risk_factors"
        type: "array<string>"
        nullable: false
      - name: "recommended_actions"
        type: "array<string>"
        nullable: false

processing:
  stream_processing:
    trigger: "5 minutes"
    batch_size: 300
    parallelism: 12
    checkpoint_interval: "5 minutes"
    
  risk_scoring:
    scoring_models: ["ensemble", "gradient_boosting", "logistic_regression"]
    ensemble_weights: [0.5, 0.3, 0.2]
    risk_categories: ["LOW", "MEDIUM", "HIGH", "CRITICAL"]
    
  monitoring:
    metrics_enabled: true
    alert_thresholds:
      processing_delay_seconds: 300
      high_risk_rate_threshold: 0.03
      error_rate_threshold: 0.01
